### PR TITLE
Remove `CMDQueryStringSerialization` dependancy

### PR DESCRIPTION
**Pull request by lionel-alves**

### CODE REVIEW

**Comment by dasmer** [comment]
nice work! :green_apple:

**Comment by ayanonagon** [comment]
Nice! How did you verify that this works?

**Comment by ayanonagon** [comment]
Also how is `ISO8601` being added?

**Comment by lionel-alves** [comment]
I have tests for that and they are passing :smile:

**Comment by lionel-alves** [comment]
Let's merge https://github.com/venmo/VENCore/pull/40 first.

**Comment by dasmer** [comment]
Thanks Lionel!

**Pull request closed without merging**
